# Generated by Django 4.0.1 on 2022-01-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_chat', '0002_liker_client_liking_liker_user_from_liker_user_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6),
        ),
    ]
