# Generated by Django 4.0.1 on 2022-01-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_chat', '0004_client_latitude_client_longitude'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
            ],
        ),
    ]
