# Generated by Django 4.0.1 on 2022-01-17 14:43

import dating_chat.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating_chat', '0007_alter_client_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', dating_chat.models.LocationManager()),
            ],
        ),
    ]
