# Generated by Django 4.0.1 on 2022-01-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating_chat', '0008_alter_client_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['latitude'], name='dating_chat_latitud_e411bb_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['longitude'], name='dating_chat_longitu_18df53_idx'),
        ),
    ]
